### ISSUE TITLE
読書会の開始時のDL用リンクがおかしい

### ISSUE THREAD

**Issue by mattn** [osyo-manga/lingr-bot-reading_vimrc#3]
https://github.com/osyo-manga/lingr-bot-reading_vimrc/blob/master/web.rb#L52

現在の raw_url は raw.githubusercontent.com になっていのでリンクが壊れています。
今後、某部屋にこられないのであればメンテ運用含めて引き取りますので、遠慮なく言って下さい。

**Comment by osyo-manga** [comment]
ありがとうございます。修正しました。

> 今後、某部屋にこられないのであればメンテ運用含めて引き取りますので、遠慮なく言って下さい。

メンテ自体を行うことは問題ないので、問題があればここで報告してもらえると助かります。

**Comment by mattn** [comment]
動作確認が出来たらしいのでcloseします。

**Comment by mattn** [comment]
ありがとうございました。

**Comment by osyo-manga** [comment]
ありがとうございました。
