### ISSUE TITLE
herokuの無料dynoの制限に対応したい

### ISSUE THREAD

**Issue by haya14busa** [osyo-manga/lingr-bot-reading_vimrc#4]
ご存知だと思いますがherokuの新料金プランに伴ってbotが24時間起きていられなくなりました．

[Herokuが新料金を発表。無料Dynoの制限が変わる - iyuichiの私的開発ログ](http://iyuichi.hatenablog.jp/entry/2015/05/14/heroku-new-pricing-free-dyno)

> Process Scheduler

そこで暫定回避策として上記の記事にも書いてある `Process Scheduler` を使用して寝かせる時間を6時間指定し，残りの時間は起きてられるようにしたいかなと思います．

reading_vimrc bot は基本的には土曜の11頃には起きてさえいればよいので毎日深夜の3:00-9:00くらいまで寝かせるとよいかなぁと思っています．

お手数かけて申し訳無さですが，heroku に process schedulerのaddonを入れて上記のように対応していただけないでしょうか? (もしくは何か代案を考えているようでしたらおねがいしますっ!) :bow:

**Comment by osyo-manga** [comment]
ありがとうございます。
時間があるときに対応したいと思います。

**Comment by haya14busa** [comment]
ありがとうございます．よろしくお願いします．

ところでこれは単なる思いつきですが，残念みながらおしょーさんはこれから読書会に参加なさらないのにメンテしていただくのはなかなか申し訳なみがあるので，
- heroku bot の移譲 or 権限誰かに付与? (やったことないですが，たしかtransferあった気がします. 権限については調べてすらいないですが..ｽｲﾏｾﾝ...)
- このリポジトリの移譲，またはライセンスあたりを明記していただいてfork or cloneして他の人がherokuなどにあげることも含めてメンテする

というような選択肢も考えられるのかなぁと思いました．いろいろ移譲するとすれば vim-jp でしょうか． もしおしょーさんもそちらのほうがよいと思う場合はどうにかよしなにやりたいな〜と思いますがどうでしょうか．

**Comment by osyo-manga** [comment]
すみません、すっかり忘れてました…。
以下のように設定したので多分大丈夫だと思います。
![](http://i.gyazo.com/92dafbd8e0f9f334136139d0ae464e51.png)

**Comment by haya14busa** [comment]
ｱ...すいませんこちらもすっかり忘れていたんですが， @zchee さんという方がAWSを提供してくださって現在そちらを使っているので heroku の方はおそらく動いてなくてもよいようになっています．
報告わすれていてすいません...

**Comment by osyo-manga** [comment]
つまり reading_vimrc-bot 自体もう必要ないということでおk？

**Comment by haya14busa** [comment]
はい，@zchee さんによるとそのハズです

**Comment by zchee** [comment]
@osyo-manga 誠に申し訳ありません．こちらにご連絡を入れなければと思いつつ，忘れてしまいました．
また，気づくのも遅くなってしまいました．

reading_vimrcは，forkさせていただき，少し変更を加え自分のAWSにて稼動中です．
また，thincaさんの手により読書会repoの方もurl変更していただいたようです．
お手間とらせてしまい，申し訳ないです．

@haya14busa フォローありがとうございました．
mentionいただいたのにチェック遅れてしまいました．失礼しました．

**Comment by zchee** [comment]
また，forkに対するライセンス表記などのご意見があればご連絡ください．
すぐに対応させていただきます．
